In [12]:
import pandas as pd 

df = pd.read_excel("Template_Data_Keluarga_Individu copy.xlsx",header=2)

In [13]:
df

,id_keluarga,desa_kelurahan,status_wilayah,sls,nama_responden,alamat,no_hp,nomor_kk,nama_kepala_keluarga,nik_kepala_keluarga,...,agama_mayoritas,jumlah_disabilitas,penerima_blt_desa,penerima_pkh,penerima_bpjs_pbi,penerima_bantuan_pangan,penerima_bnpt_sembako,penerima_pip,penerima_mbg,art_tidak_lagi_menerima
0,KLG-1-001,Desa Malalanda,Desa,SLS 003,Usman Salim,"Jl. Pattimura No. 51, RT 03/02",8660512102,740800201709800001,Usman Salim,740800281812940010,...,Islam,0,Tidak,Tidak,Ya,Tidak,Tidak,Tidak,Ya,0
1,KLG-1-002,Desa Malalanda,Desa,SLS 005,Putra Ismail,"Jl. Diponegoro No. 58, RT 02/02",8818629549,740800180101640002,Putra Ismail,740800160912850020,...,Islam,1,Ya,Tidak,Tidak,Ya,Tidak,Ya,Tidak,0
2,KLG-1-003,Desa Malalanda,Desa,SLS 004,Fajar Hasan,"Jl. Sudirman No. 68, RT 05/02",8238767018,740800162609880003,Fajar Hasan,740800181409830030,...,Islam,0,Tidak,Ya,Ya,Tidak,Tidak,Tidak,Tidak,0
3,KLG-1-004,Desa Malalanda,Desa,SLS 001,Noor Saputra,"Jl. Kartini No. 80, RT 01/01",8126868746,740800181305900004,Noor Saputra,740800192306790040,...,Islam,0,Ya,Tidak,Ya,Ya,Tidak,Tidak,Tidak,0
4,KLG-1-005,Desa Malalanda,Desa,SLS 003,Muh. Hasan,"Jl. Diponegoro No. 70, RT 03/02",8362158604,740800101804870005,Muh. Hasan,740800271711910050,...,Islam,0,Tidak,Tidak,Tidak,Tidak,Ya,Ya,Ya,0
5,KLG-1-006,Desa Malalanda,Desa,SLS 005,Toni Yusuf,"Jl. Pattimura No. 55, RT 03/03",8618057276,740800180806640006,Toni Yusuf,740800301307700060,...,Islam,0,Tidak,Tidak,Tidak,Tidak,Tidak,Ya,Ya,1
6,KLG-1-007,Desa Malalanda,Desa,SLS 005,Putra Ismail,"Jl. Diponegoro No. 62, RT 05/01",8980121102,740800202705610007,Putra Ismail,740800182708760070,...,Kepercayaan,0,Ya,Ya,Tidak,Tidak,Tidak,Tidak,Ya,0
7,KLG-1-008,Desa Malalanda,Desa,SLS 002,Oki Ismail,"Jl. Sudirman No. 23, RT 02/03",8735407316,740800250706650008,Oki Ismail,740800161011930080,...,Islam,0,Tidak,Ya,Ya,Ya,Tidak,Tidak,Tidak,0
8,KLG-2-001,Desa Laangke,Desa,SLS 004,Toni Saputra,"Jl. Merdeka No. 32, RT 02/01",8532682421,740801190809700009,Toni Saputra,740801212009750090,...,Islam,0,Tidak,Tidak,Tidak,Tidak,Ya,Tidak,Tidak,0
9,KLG-2-002,Desa Laangke,Desa,SLS 002,Hadi Nugraha,"Jl. Mawar No. 97, RT 02/03",8998870639,740801261202830010,Hadi Nugraha,740801220805890100,...,Islam,0,Tidak,Ya,Ya,Tidak,Ya,Tidak,Ya,0
10,KLG-2-003,Desa Laangke,Desa,SLS 004,Budi Utami,"Jl. Pattimura No. 89, RT 05/03",8599232172,740801212808670011,Budi Utami,740801190607910110,...,Islam,0,Tidak,Tidak,Ya,Tidak,Tidak,Tidak,Tidak,0
11,KLG-2-004,Desa Laangke,Desa,SLS 002,Noor Pratama,"Jl. Merdeka No. 19, RT 05/03",8544645203,740801232503620012,Noor Pratama,740801241601840120,...,Islam,0,Tidak,Tidak,Ya,Tidak,Tidak,Ya,Tidak,0
12,KLG-2-005,Desa Laangke,Desa,SLS 003,La Ode Hasan,"Jl. Nusantara No. 39, RT 03/01",8439297473,740801241906780013,La Ode Hasan,740801212605950130,...,Islam,0,Tidak,Tidak,Tidak,Ya,Ya,Tidak,Ya,0
13,KLG-2-006,Desa Laangke,Desa,SLS 001,Wahyu Ramadhan,"Jl. Pattimura No. 40, RT 01/02",8719642412,740801162503900014,Wahyu Ramadhan,740801291009710140,...,Islam,0,Tidak,Tidak,Tidak,Ya,Tidak,Ya,Tidak,0
14,KLG-2-007,Desa Laangke,Desa,SLS 003,Noor Salim,"Jl. Melati No. 12, RT 02/03",8535048978,740801190605840015,Noor Salim,740801160307820150,...,Islam,0,Tidak,Tidak,Tidak,Tidak,Tidak,Tidak,Tidak,0
15,KLG-2-008,Desa Laangke,Desa,SLS 002,Budi Wulandari,"Jl. Merdeka No. 11, RT 02/02",8815670826,740801150104760016,Budi Wulandari,740801102104700160,...,Kristen Protestan,0,Ya,Ya,Tidak,Tidak,Tidak,Tidak,Ya,0
16,KLG-2-009,Desa Laangke,Desa,SLS 003,Eko Rasyid,"Jl. Kartini No. 52, RT 02/03",8472690090,740801220904860017,Eko Rasyid,740801151901910170,...,Islam,0,Tidak,Tidak,Tidak,Tidak,Tidak,Tidak,Tidak,0
17,KLG-3-001,Kelurahan Lakonea,Kelurahan,SLS 002,Muh. Pratama,"Jl. Diponegoro No. 15, RT 05/01",8525568427,740802270102700018,Muh. Pratama,740802110711990180,...,Islam,0,Tidak,Ya,Ya,Tidak,Ya,Tidak,Tidak,0
18,KLG-3-002,Kelurahan Lakonea,Kelurahan,SLS 001,Ahmad Arifin,"Jl. Nusantara No. 94, RT 03/03",8177050221,740802291001880019,Ahmad Arifin,740802231804960190,...,Islam,0,Tidak,Tidak,Ya,Tidak,Tidak,Ya,Tidak,0
19,KLG-3-003,Kelurahan Lakonea,Kelurahan,SLS 002,Wahyu Ismail,"Jl. Mawar No. 12, RT 02/03",8425935173,740802302610810020,Wahyu Ismail,740802150309990200,...,Kristen Protestan,0,Tidak,Tidak,Tidak,Tidak,Tidak,Ya,Ya,0
20,KLG-3-004,Kelurahan Lakonea,Kelurahan,SLS 004,Usman Setiawan,"Jl. Pattimura No. 28, RT 04/03",8885994901,740802151205780021,Usman Setiawan,740802302702870210,...,Islam,0,Tidak,Ya,Tidak,Ya,Tidak,Tidak,Tidak,0
21,KLG-3-005,Kelurahan Lakonea,Kelurahan,SLS 003,Slamet Rasyid,"Jl. Merdeka No. 55, RT 05/03",8666804631,740802250908740022,Slamet Rasyid,740802301311880220,...,Buddha,0,Tidak,Tidak,Ya,Ya,Tidak,Tidak,Tidak,0
22,KLG-3-006,Kelurahan Lakonea,Kelurahan,SLS 005,Putra Karim,"Jl. Pattimura No. 18, RT 04/01",8847652400,740802201506610023,Putra Karim,740802241706920230,...,Islam,0,Tidak,Tidak,Ya,Ya,Tidak,Tidak,Tidak,0
23,KLG-3-007,Kelurahan Lakonea,Kelurahan,SLS 003,Usman Arifin,"Jl. Diponegoro No. 55, RT 01/02",8622525293,740802120311810024,Usman Arifin,740802270806980240,...,Islam,0,Tidak,Ya,Tidak,Tidak,Tidak,Ya,Ya,0
24,KLG-3-008,Kelurahan Lakonea,Kelurahan,SLS 002,Slamet Setiawan,"Jl. Kartini No. 54, RT 03/02",8631331167,740802251302640025,Slamet Setiawan,740802201606920250,...,Islam,1,Tidak,Tidak,Ya,Ya,Ya,Tidak,Ya,0
25,KLG-3-009,Kelurahan Lakonea,Kelurahan,SLS 002,Oki Sari,"Jl. Merdeka No. 40, RT 03/02",8284997046,740802232209670026,Oki Sari,740802131105850260,...,Islam,0,Tidak,Ya,Ya,Tidak,Tidak,Tidak,Tidak,0
26,KLG-3-010,Kelurahan Lakonea,Kelurahan,SLS 003,Slamet Setiawan,"Jl. Kartini No. 13, RT 05/02",8174158569,740802192112890027,Slamet Setiawan,740802232610810270,...,Islam,0,Tidak,Ya,Ya,Tidak,Tidak,Tidak,Tidak,0
27,KLG-3-011,Kelurahan Lakonea,Kelurahan,SLS 004,Joko Utami,"Jl. Kartini No. 10, RT 01/02",8925138757,740802281507860028,Joko Utami,740802270308740280,...,Islam,1,Tidak,Ya,Ya,Tidak,Tidak,Tidak,Tidak,0

In [15]:
import pandas as pd 

df = pd.read_excel("Template_Data_Keluarga_Individu.xlsx",header=2)

In [16]:
df

,id_keluarga,desa_kelurahan,status_wilayah,sls,nama_responden,alamat,no_hp,nomor_kk,nama_kepala_keluarga,nik_kepala_keluarga,...,agama_mayoritas,jumlah_disabilitas,penerima_blt_desa,penerima_pkh,penerima_bpjs_pbi,penerima_bantuan_pangan,penerima_bnpt_sembako,penerima_pip,penerima_mbg,art_tidak_lagi_menerima
0,KLG-1-001,Desa Malalanda,Desa,SLS 003,Usman Salim,"Jl. Pattimura No. 51, RT 03/02",8660512102,740800201709800001,Usman Salim,740800281812940010,...,Islam,0,Tidak,Tidak,Ya,Tidak,Tidak,Tidak,Ya,0
1,KLG-1-002,Desa Malalanda,Desa,SLS 005,Putra Ismail,"Jl. Diponegoro No. 58, RT 02/02",8818629549,740800180101640002,Putra Ismail,740800160912850020,...,Islam,1,Ya,Tidak,Tidak,Ya,Tidak,Ya,Tidak,0
2,KLG-1-003,Desa Malalanda,Desa,SLS 004,Fajar Hasan,"Jl. Sudirman No. 68, RT 05/02",8238767018,740800162609880003,Fajar Hasan,740800181409830030,...,Islam,0,Tidak,Ya,Ya,Tidak,Tidak,Tidak,Tidak,0
3,KLG-1-004,Desa Malalanda,Desa,SLS 001,Noor Saputra,"Jl. Kartini No. 80, RT 01/01",8126868746,740800181305900004,Noor Saputra,740800192306790040,...,Islam,0,Ya,Tidak,Ya,Ya,Tidak,Tidak,Tidak,0
4,KLG-1-005,Desa Malalanda,Desa,SLS 003,Muh. Hasan,"Jl. Diponegoro No. 70, RT 03/02",8362158604,740800101804870005,Muh. Hasan,740800271711910050,...,Islam,0,Tidak,Tidak,Tidak,Tidak,Ya,Ya,Ya,0
5,KLG-1-006,Desa Malalanda,Desa,SLS 005,Toni Yusuf,"Jl. Pattimura No. 55, RT 03/03",8618057276,740800180806640006,Toni Yusuf,740800301307700060,...,Islam,0,Tidak,Tidak,Tidak,Tidak,Tidak,Ya,Ya,1
6,KLG-1-007,Desa Malalanda,Desa,SLS 005,Putra Ismail,"Jl. Diponegoro No. 62, RT 05/01",8980121102,740800202705610007,Putra Ismail,740800182708760070,...,Kepercayaan,0,Ya,Ya,Tidak,Tidak,Tidak,Tidak,Ya,0
7,KLG-1-008,Desa Malalanda,Desa,SLS 002,Oki Ismail,"Jl. Sudirman No. 23, RT 02/03",8735407316,740800250706650008,Oki Ismail,740800161011930080,...,Islam,0,Tidak,Ya,Ya,Ya,Tidak,Tidak,Tidak,0
8,KLG-2-001,Desa Laangke,Desa,SLS 004,Toni Saputra,"Jl. Merdeka No. 32, RT 02/01",8532682421,740801190809700009,Toni Saputra,740801212009750090,...,Islam,0,Tidak,Tidak,Tidak,Tidak,Ya,Tidak,Tidak,0
9,KLG-2-002,Desa Laangke,Desa,SLS 002,Hadi Nugraha,"Jl. Mawar No. 97, RT 02/03",8998870639,740801261202830010,Hadi Nugraha,740801220805890100,...,Islam,0,Tidak,Ya,Ya,Tidak,Ya,Tidak,Ya,0
10,KLG-2-003,Desa Laangke,Desa,SLS 004,Budi Utami,"Jl. Pattimura No. 89, RT 05/03",8599232172,740801212808670011,Budi Utami,740801190607910110,...,Islam,0,Tidak,Tidak,Ya,Tidak,Tidak,Tidak,Tidak,0
11,KLG-2-004,Desa Laangke,Desa,SLS 002,Noor Pratama,"Jl. Merdeka No. 19, RT 05/03",8544645203,740801232503620012,Noor Pratama,740801241601840120,...,Islam,0,Tidak,Tidak,Ya,Tidak,Tidak,Ya,Tidak,0
12,KLG-2-005,Desa Laangke,Desa,SLS 003,La Ode Hasan,"Jl. Nusantara No. 39, RT 03/01",8439297473,740801241906780013,La Ode Hasan,740801212605950130,...,Islam,0,Tidak,Tidak,Tidak,Ya,Ya,Tidak,Ya,0
13,KLG-2-006,Desa Laangke,Desa,SLS 001,Wahyu Ramadhan,"Jl. Pattimura No. 40, RT 01/02",8719642412,740801162503900014,Wahyu Ramadhan,740801291009710140,...,Islam,0,Tidak,Tidak,Tidak,Ya,Tidak,Ya,Tidak,0
14,KLG-2-007,Desa Laangke,Desa,SLS 003,Noor Salim,"Jl. Melati No. 12, RT 02/03",8535048978,740801190605840015,Noor Salim,740801160307820150,...,Islam,0,Tidak,Tidak,Tidak,Tidak,Tidak,Tidak,Tidak,0
15,KLG-2-008,Desa Laangke,Desa,SLS 002,Budi Wulandari,"Jl. Merdeka No. 11, RT 02/02",8815670826,740801150104760016,Budi Wulandari,740801102104700160,...,Kristen Protestan,0,Ya,Ya,Tidak,Tidak,Tidak,Tidak,Ya,0
16,KLG-2-009,Desa Laangke,Desa,SLS 003,Eko Rasyid,"Jl. Kartini No. 52, RT 02/03",8472690090,740801220904860017,Eko Rasyid,740801151901910170,...,Islam,0,Tidak,Tidak,Tidak,Tidak,Tidak,Tidak,Tidak,0
17,KLG-3-001,Kelurahan Lakonea,Kelurahan,SLS 002,Muh. Pratama,"Jl. Diponegoro No. 15, RT 05/01",8525568427,740802270102700018,Muh. Pratama,740802110711990180,...,Islam,0,Tidak,Ya,Ya,Tidak,Ya,Tidak,Tidak,0
18,KLG-3-002,Kelurahan Lakonea,Kelurahan,SLS 001,Ahmad Arifin,"Jl. Nusantara No. 94, RT 03/03",8177050221,740802291001880019,Ahmad Arifin,740802231804960190,...,Islam,0,Tidak,Tidak,Ya,Tidak,Tidak,Ya,Tidak,0
19,KLG-3-003,Kelurahan Lakonea,Kelurahan,SLS 002,Wahyu Ismail,"Jl. Mawar No. 12, RT 02/03",8425935173,740802302610810020,Wahyu Ismail,740802150309990200,...,Kristen Protestan,0,Tidak,Tidak,Tidak,Tidak,Tidak,Ya,Ya,0
20,KLG-3-004,Kelurahan Lakonea,Kelurahan,SLS 004,Usman Setiawan,"Jl. Pattimura No. 28, RT 04/03",8885994901,740802151205780021,Usman Setiawan,740802302702870210,...,Islam,0,Tidak,Ya,Tidak,Ya,Tidak,Tidak,Tidak,0
21,KLG-3-005,Kelurahan Lakonea,Kelurahan,SLS 003,Slamet Rasyid,"Jl. Merdeka No. 55, RT 05/03",8666804631,740802250908740022,Slamet Rasyid,740802301311880220,...,Buddha,0,Tidak,Tidak,Ya,Ya,Tidak,Tidak,Tidak,0
22,KLG-3-006,Kelurahan Lakonea,Kelurahan,SLS 005,Putra Karim,"Jl. Pattimura No. 18, RT 04/01",8847652400,740802201506610023,Putra Karim,740802241706920230,...,Islam,0,Tidak,Tidak,Ya,Ya,Tidak,Tidak,Tidak,0
23,KLG-3-007,Kelurahan Lakonea,Kelurahan,SLS 003,Usman Arifin,"Jl. Diponegoro No. 55, RT 01/02",8622525293,740802120311810024,Usman Arifin,740802270806980240,...,Islam,0,Tidak,Ya,Tidak,Tidak,Tidak,Ya,Ya,0
24,KLG-3-008,Kelurahan Lakonea,Kelurahan,SLS 002,Slamet Setiawan,"Jl. Kartini No. 54, RT 03/02",8631331167,740802251302640025,Slamet Setiawan,740802201606920250,...,Islam,1,Tidak,Tidak,Ya,Ya,Ya,Tidak,Ya,0
25,KLG-3-009,Kelurahan Lakonea,Kelurahan,SLS 002,Oki Sari,"Jl. Merdeka No. 40, RT 03/02",8284997046,740802232209670026,Oki Sari,740802131105850260,...,Islam,0,Tidak,Ya,Ya,Tidak,Tidak,Tidak,Tidak,0
26,KLG-3-010,Kelurahan Lakonea,Kelurahan,SLS 003,Slamet Setiawan,"Jl. Kartini No. 13, RT 05/02",8174158569,740802192112890027,Slamet Setiawan,740802232610810270,...,Islam,0,Tidak,Ya,Ya,Tidak,Tidak,Tidak,Tidak,0
27,KLG-3-011,Kelurahan Lakonea,Kelurahan,SLS 004,Joko Utami,"Jl. Kartini No. 10, RT 01/02",8925138757,740802281507860028,Joko Utami,740802270308740280,...,Islam,1,Tidak,Ya,Ya,Tidak,Tidak,Tidak,Tidak,0